language: go
env:
  global:
    - MYSQL_FLAVOR=MariaDB
  matrix:
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
    - MAKE_TARGET=small_integration_test
before_install:
  - bash -v travis/dependencies.sh
install:
  - bash -v bootstrap.sh
script:
  - source dev.env
  - travis_retry make $MAKE_TARGET
